// App-wide, persisted settings for VibeContent.
// These settings are REAL: they are read right before content generation and
// change what is sent to the RAG service (grounding strictness, retrieval size,
// threshold) and how generated content is handled (privacy controls).

export interface GroundingSettings {
  /** Preset on the 1..5 scale, or 0 when the user fine-tuned the values manually. */
  level: number;
  strictGrounding: boolean;
  /** Relevance threshold 0..1. Higher = only strongly relevant chunks are used. */
  threshold: number;
  /** How many knowledge chunks are retrieved. */
  topK: number;
  includeSources: boolean;
  useReranker: boolean;
  useHybrid: boolean;
}

export interface PrivacySettings {
  /** When off, content is generated by the local offline engine only (no data leaves the app). */
  allowRemoteGeneration: boolean;
  /** When off, brief/brand context is not appended to the query sent to the RAG service. */
  includeBrandContextInQuery: boolean;
  /** When off, verbatim source excerpts are omitted from the generated draft body. */
  includeSourceExcerpts: boolean;
  /** When off, generated drafts are not written to the database. */
  persistGeneratedDrafts: boolean;
}

export interface AppSettings {
  defaultLanguage: 'id' | 'en';
  grounding: GroundingSettings;
  privacy: PrivacySettings;
}

/** The 5-point grounding scale. Level 3 is the balanced default. */
export const GROUNDING_PRESETS: Record<number, Omit<GroundingSettings, 'level'>> = {
  1: { strictGrounding: false, threshold: 0.12, topK: 8, includeSources: true, useReranker: false, useHybrid: true },
  2: { strictGrounding: false, threshold: 0.22, topK: 8, includeSources: true, useReranker: false, useHybrid: true },
  3: { strictGrounding: true, threshold: 0.35, topK: 6, includeSources: true, useReranker: true, useHybrid: true },
  4: { strictGrounding: true, threshold: 0.5, topK: 5, includeSources: true, useReranker: true, useHybrid: true },
  5: { strictGrounding: true, threshold: 0.65, topK: 4, includeSources: true, useReranker: true, useHybrid: true }
};

export const GROUNDING_LEVEL_LABELS: Record<number, string> = {
  0: 'Kustom',
  1: 'Sangat Longgar',
  2: 'Longgar',
  3: 'Seimbang',
  4: 'Ketat',
  5: 'Sangat Ketat'
};

export const DEFAULT_SETTINGS: AppSettings = {
  defaultLanguage: 'id',
  grounding: { level: 3, ...GROUNDING_PRESETS[3] },
  privacy: {
    allowRemoteGeneration: true,
    includeBrandContextInQuery: true,
    includeSourceExcerpts: true,
    persistGeneratedDrafts: true
  }
};

/** Build a grounding object from a preset level. */
export function groundingForLevel(level: number): GroundingSettings {
  const clamped = Math.min(5, Math.max(1, Math.round(level)));
  return { level: clamped, ...GROUNDING_PRESETS[clamped] };
}

/**
 * Coerce an arbitrary value (e.g. the JSONB doc returned by the API) into a
 * complete, validated AppSettings object, filling missing fields with defaults.
 */
export function normalizeSettings(raw: unknown): AppSettings {
  const base = DEFAULT_SETTINGS;
  if (!raw || typeof raw !== 'object') return base;
  const input = raw as Partial<AppSettings>;
  const g = (input.grounding || {}) as Partial<GroundingSettings>;
  const p = (input.privacy || {}) as Partial<PrivacySettings>;
  return {
    defaultLanguage: input.defaultLanguage === 'en' ? 'en' : 'id',
    grounding: {
      level: typeof g.level === 'number' ? g.level : base.grounding.level,
      strictGrounding: typeof g.strictGrounding === 'boolean' ? g.strictGrounding : base.grounding.strictGrounding,
      threshold: typeof g.threshold === 'number' ? Math.min(1, Math.max(0, g.threshold)) : base.grounding.threshold,
      topK: typeof g.topK === 'number' ? Math.min(15, Math.max(1, Math.round(g.topK))) : base.grounding.topK,
      includeSources: typeof g.includeSources === 'boolean' ? g.includeSources : base.grounding.includeSources,
      useReranker: typeof g.useReranker === 'boolean' ? g.useReranker : base.grounding.useReranker,
      useHybrid: typeof g.useHybrid === 'boolean' ? g.useHybrid : base.grounding.useHybrid
    },
    privacy: {
      allowRemoteGeneration: typeof p.allowRemoteGeneration === 'boolean' ? p.allowRemoteGeneration : base.privacy.allowRemoteGeneration,
      includeBrandContextInQuery: typeof p.includeBrandContextInQuery === 'boolean' ? p.includeBrandContextInQuery : base.privacy.includeBrandContextInQuery,
      includeSourceExcerpts: typeof p.includeSourceExcerpts === 'boolean' ? p.includeSourceExcerpts : base.privacy.includeSourceExcerpts,
      persistGeneratedDrafts: typeof p.persistGeneratedDrafts === 'boolean' ? p.persistGeneratedDrafts : base.privacy.persistGeneratedDrafts
    }
  };
}

/** Payload shape sent to our /api/rag/* proxy and forwarded to the RAG service. */
export interface RagOptionsPayload {
  top_k?: number;
  strict_grounding?: boolean;
  threshold?: number;
  include_sources?: boolean;
  use_reranker?: boolean;
  use_hybrid?: boolean;
}

/** Map our grounding settings to the RAG service's QueryOptions keys. */
export function toRagOptions(grounding: GroundingSettings): RagOptionsPayload {
  return {
    top_k: grounding.topK,
    strict_grounding: grounding.strictGrounding,
    threshold: grounding.threshold,
    include_sources: grounding.includeSources,
    use_reranker: grounding.useReranker,
    use_hybrid: grounding.useHybrid
  };
}

/* ── Privacy helpers ───────────────────────────────────────────────────
 * Pure functions so every privacy switch has one clearly-testable effect.
 */

/** Placeholder that replaces a verbatim source excerpt when excerpt sharing is off. */
export const REDACTED_EXCERPT = '[kutipan sumber disembunyikan oleh pengaturan privasi]';

export interface BriefQueryParts {
  title: string;
  keyMessage: string;
  targetAudience?: string;
  tone?: string;
  channel?: string;
  format?: string;
}

/**
 * Build the retrieval query. When `includeBrandContextInQuery` is off, only the
 * title and key message are sent — audience/tone/channel/format stay in the app.
 */
export function buildRetrievalQuery(settings: AppSettings, parts: BriefQueryParts): string {
  const base = [parts.title, parts.keyMessage];
  // Only semantically useful context is added. UI tokens such as the output
  // format ('copy_caption') or tone pollute vector retrieval and reduce precision,
  // so they are intentionally excluded even when brand context is enabled.
  const context = settings.privacy.includeBrandContextInQuery
    ? [parts.targetAudience, parts.channel]
    : [];
  return [...base, ...context].filter(Boolean).join(' ');
}

/** Whether content generation may contact the remote RAG service. */
export function shouldCallRemote(settings: AppSettings): boolean {
  return settings.privacy.allowRemoteGeneration;
}

/** Whether a generated draft may be written to the database. */
export function shouldPersistDraft(settings: AppSettings): boolean {
  return settings.privacy.persistGeneratedDrafts;
}

/** Strip verbatim source excerpts when the user has disabled excerpt sharing. */
export function redactCitationExcerpts<T extends { excerpt: string }>(settings: AppSettings, citations: T[]): T[] {
  if (settings.privacy.includeSourceExcerpts) return citations;
  return citations.map(citation => ({ ...citation, excerpt: REDACTED_EXCERPT }));
}

/** Human-readable summary of exactly what leaves the app, for the privacy panel. */
export function outboundDataSummary(settings: AppSettings, grounding: GroundingSettings): string[] {
  if (!settings.privacy.allowRemoteGeneration) {
    return ['Mode privasi tinggi: tidak ada data yang dikirim keluar aplikasi.'];
  }
  const items = [
    settings.privacy.includeBrandContextInQuery
      ? 'Teks brief, pesan kunci, dan konteks merek (audiens, nada, kanal, format).'
      : 'Hanya judul dan pesan kunci (konteks merek tidak dikirim).',
    `Pengaturan grounding: ambang ${(grounding.threshold * 100).toFixed(0)}%, top-k ${grounding.topK}, strict ${grounding.strictGrounding ? 'aktif' : 'nonaktif'}.`
  ];
  items.push(settings.privacy.includeSourceExcerpts
    ? 'Kutipan sumber verbatim dapat ditampilkan pada draf.'
    : 'Kutipan sumber verbatim disembunyikan (hanya metadata sumber).');
  items.push(settings.privacy.persistGeneratedDrafts
    ? 'Draf hasil generasi disimpan ke database.'
    : 'Draf hasil generasi TIDAK disimpan ke database.');
  return items;
}
