import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
process.env.NODE_ENV = 'test';
const { default: app } = await import('./index.ts');
const { pool, runMigrations, clearAllData, hashPassword } = await import('./database.ts');
const server = app.listen(0);
await new Promise<void>(resolve => server.once('listening', resolve));
const base = `http://127.0.0.1:${(server.address() as {port:number}).port}`;
async function api(method:string,path:string,body?:unknown,cookie?:string) {
  const response=await fetch(`${base}${path}`,{method,headers:{'Content-Type':'application/json',Origin:'http://localhost:5173',...(cookie?{Cookie:cookie}:{})},body:body===undefined?undefined:JSON.stringify(body)});
  return {status:response.status,data:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]||''};
}
test.before(async()=>{await runMigrations();await clearAllData();await pool.query('DELETE FROM companies');});
test.after(async()=>{await clearAllData();await pool.query('DELETE FROM companies');server.close();await pool.end();});

test('three roles: login, company isolation, workspace memberships, global management',async()=>{
  const pass=`longpass-${randomUUID()}`;
  const email=`root-${randomUUID()}@test.dev`;
  await pool.query("INSERT INTO users(id,name,email,password_hash,global_role) VALUES($1,'Root',$2,$3,'superadmin')",[`usr-${randomUUID()}`,email,await hashPassword(pass)]);
  const root=await api('POST','/api/auth/login',{email,password:pass});
  assert.equal(root.status,200);assert.equal(root.data.role,'superadmin');assert.ok(root.cookie);
  const co=await api('POST','/api/admin/companies',{name:'Alpha'},root.cookie);
  assert.equal(co.status,201);
  const other=await api('POST','/api/admin/companies',{name:'Beta'},root.cookie);
  assert.equal(other.status,201);
  assert.equal((await api('POST','/api/admin/users',{name:'Orphan',email:`orphan-${randomUUID()}@test.dev`,password:pass,role:'creator'},root.cookie)).status,400);
  const corpEmail=`corp-${randomUUID()}@test.dev`;
  const corp=await api('POST','/api/admin/users',{name:'Corp',email:corpEmail,password:pass,role:'corporate',companyId:co.data.id},root.cookie);
  assert.equal(corp.status,201);
  const ws=await api('POST','/api/admin/workspaces',{companyId:co.data.id,name:'Alpha One',code:`A${randomUUID().slice(0,8)}`,sector:'Water',city:'Bandung'},root.cookie);
  const wsOther=await api('POST','/api/admin/workspaces',{companyId:other.data.id,name:'Beta One',code:`B${randomUUID().slice(0,8)}`,sector:'Water',city:'Bandung'},root.cookie);
  assert.equal(ws.status,201);assert.equal(wsOther.status,201);
  const manager=await api('POST','/api/auth/login',{email:corpEmail,password:pass});
  assert.equal(manager.status,200);assert.equal(manager.data.role,'corporate');assert.equal(manager.data.companyId,co.data.id);
  assert.equal((await api('PUT','/api/corporate/settings',{name:'Hacked'},root.cookie)).status,403);
  assert.equal((await api('PUT','/api/corporate/settings',{name:'  '},manager.cookie)).status,400);
  assert.equal((await api('PUT','/api/corporate/settings',{name:'Alpha Updated',companyId:other.data.id},manager.cookie)).status,200);
  assert.equal((await api('GET','/api/corporate/dashboard',undefined,manager.cookie)).data.company.name,'Alpha Updated');
  assert.equal((await api('GET','/api/admin/companies',undefined,root.cookie)).data.find((c:{id:string})=>c.id===other.data.id).name,'Beta');
  assert.equal((await api('PUT','/api/auth/password',{currentPassword:'wrong',newPassword:'updated-pass-123'},manager.cookie)).status,403);
  assert.equal((await api('PUT','/api/auth/password',{currentPassword:pass,newPassword:'short'},manager.cookie)).status,400);
  assert.equal((await api('PUT','/api/auth/password',{currentPassword:pass,newPassword:'updated-pass-123',userId:root.data.id},manager.cookie)).status,200);
  assert.equal((await api('POST','/api/auth/login',{email:corpEmail,password:pass})).status,401);
  assert.equal((await api('POST','/api/auth/login',{email:corpEmail,password:'updated-pass-123'})).status,200);
  assert.equal((await api('POST','/api/auth/login',{email,password:pass})).status,200,'password update must not touch superadmin');
  assert.deepEqual(manager.data.workspaces.map((w:{id:string})=>w.id),[ws.data.id]);
  assert.equal((await api('GET','/api/corporate/dashboard',undefined,root.cookie)).status,403);
  assert.equal((await api('GET','/api/admin/users',undefined,manager.cookie)).status,403);
  assert.equal((await api('GET','/api/admin/audit',undefined,manager.cookie)).status,403);
  assert.equal((await api('GET','/api/admin/audit',undefined,root.cookie)).status,200);
  assert.equal((await api('GET',`/api/bootstrap?workspaceId=${wsOther.data.id}`,undefined,manager.cookie)).status,403);
  const created=await api('POST','/api/corporate/workspaces',{name:'Alpha Two',code:`C${randomUUID().slice(0,8)}`,sector:'Water',city:'Bandung'},manager.cookie);
  assert.equal(created.status,201);
  const editedWs=await api('PUT',`/api/corporate/workspaces/${created.data.id}`,{name:'Alpha Two Renamed',code:created.data.code,sector:'Water',city:'Jakarta'},manager.cookie);
  assert.equal(editedWs.status,200);assert.equal(editedWs.data.city,'Jakarta');
  assert.equal((await api('PUT',`/api/corporate/workspaces/${wsOther.data.id}`,{name:'Hack',code:'HACK',sector:'X',city:'Y'},manager.cookie)).status,404,'foreign workspace cannot be edited');
  const tmpWs=await api('POST','/api/corporate/workspaces',{name:'Temp WS',code:`T${randomUUID().slice(0,8)}`,sector:'Water',city:'Bandung'},manager.cookie);
  assert.equal((await api('DELETE',`/api/corporate/workspaces/${tmpWs.data.id}`,undefined,manager.cookie)).status,200);
  assert.equal((await api('DELETE',`/api/corporate/workspaces/${tmpWs.data.id}`,undefined,manager.cookie)).status,404);
  assert.equal((await api('DELETE',`/api/corporate/workspaces/${wsOther.data.id}`,undefined,manager.cookie)).status,404);
  const tmpCreator=await api('POST','/api/corporate/users',{name:'Temp Creator',email:`tmpc-${randomUUID()}@test.dev`,password:pass},manager.cookie);
  assert.equal(tmpCreator.status,201);
  assert.equal((await api('PUT',`/api/corporate/users/${tmpCreator.data.id}`,{name:'Temp Renamed',email:tmpCreator.data.email},manager.cookie)).status,200);
  assert.equal((await api('PUT',`/api/corporate/users/${tmpCreator.data.id}`,{name:'Temp',email:tmpCreator.data.email,password:'new-pass-12345'},manager.cookie)).status,200);
  assert.equal((await api('POST','/api/auth/login',{email:tmpCreator.data.email,password:'new-pass-12345'})).status,200);
  assert.equal((await api('PUT',`/api/corporate/users/${tmpCreator.data.id}`,{name:'Hack',email:tmpCreator.data.email},root.cookie)).status,403,'superadmin cannot edit company creator through corporate route');
  assert.equal((await api('PUT',`/api/corporate/users/${root.data.id}`,{name:'Hack',email},manager.cookie)).status,404,'manager cannot edit another company user');
  assert.equal((await api('DELETE',`/api/corporate/users/${tmpCreator.data.id}`,undefined,manager.cookie)).status,200);
  assert.equal((await api('DELETE',`/api/corporate/users/${tmpCreator.data.id}`,undefined,manager.cookie)).status,404);
  assert.equal((await api('GET',`/api/bootstrap?workspaceId=${created.data.id}`,undefined,manager.cookie)).status,200);
  const plottedEmail=`plotted-${randomUUID()}@test.dev`;
  const plotted=await api('POST','/api/corporate/users',{name:'Plotted',email:plottedEmail,password:pass},manager.cookie);
  assert.equal(plotted.status,201);
  assert.deepEqual(plotted.data.workspaceIds,[]);
  assert.equal((await api('PUT',`/api/corporate/users/${plotted.data.id}/workspaces`,{workspaceIds:[ws.data.id,created.data.id]},manager.cookie)).status,200);
  const globalAccess=await api('GET','/api/admin/memberships',undefined,root.cookie);
  assert.equal(globalAccess.status,200);
  assert.ok(globalAccess.data.some((m:{userId:string;workspaceId:string})=>m.userId===plotted.data.id&&m.workspaceId===ws.data.id));
  assert.equal((await api('GET','/api/admin/memberships',undefined,manager.cookie)).status,403);
  assert.equal((await api('POST','/api/admin/memberships',{userId:plotted.data.id,workspaceId:wsOther.data.id},root.cookie)).status,409,'creator cannot cross companies');
  assert.equal((await api('POST','/api/admin/memberships',{userId:plotted.data.id,workspaceId:ws.data.id},manager.cookie)).status,403);
  assert.equal((await api('DELETE',`/api/admin/memberships/${ws.data.id}/${plotted.data.id}`,undefined,manager.cookie)).status,403);
  assert.equal((await api('DELETE',`/api/admin/memberships/${ws.data.id}/${plotted.data.id}`,undefined,root.cookie)).status,200);
  assert.equal((await api('DELETE',`/api/admin/memberships/${created.data.id}/${plotted.data.id}`,undefined,root.cookie)).status,409,'last creator assignment retained');
  assert.equal((await api('POST','/api/admin/memberships',{userId:plotted.data.id,workspaceId:ws.data.id},root.cookie)).status,201);
  const companyUsers=await api('GET','/api/corporate/users',undefined,manager.cookie);
  assert.equal(companyUsers.status,200);
  assert.deepEqual(new Set(companyUsers.data.find((u:{id:string})=>u.id===plotted.data.id).workspaceIds),new Set([ws.data.id,created.data.id]));
  const plottedLogin=await api('POST','/api/auth/login',{email:plottedEmail,password:pass});
  assert.deepEqual(new Set(plottedLogin.data.workspaces.map((w:{id:string})=>w.id)),new Set([ws.data.id,created.data.id]));
  assert.equal((await api('PUT',`/api/corporate/users/${plotted.data.id}/workspaces`,{workspaceIds:[created.data.id]},manager.cookie)).status,200);
  assert.deepEqual((await api('GET','/api/auth/me',undefined,plottedLogin.cookie)).data.workspaces.map((w:{id:string})=>w.id),[created.data.id]);
  assert.equal((await api('PUT',`/api/corporate/users/${plotted.data.id}/workspaces`,{workspaceIds:[wsOther.data.id]},manager.cookie)).status,403);
  assert.equal((await api('PUT',`/api/corporate/users/${plotted.data.id}/workspaces`,{workspaceIds:[]},manager.cookie)).status,200,'creator may remain unassigned but manageable');
  assert.deepEqual((await api('GET','/api/corporate/users',undefined,manager.cookie)).data.find((u:{id:string})=>u.id===plotted.data.id).workspaceIds,[]);
  assert.equal((await api('PUT',`/api/corporate/users/${plotted.data.id}/workspaces`,{workspaceIds:[ws.data.id,created.data.id]},manager.cookie)).status,200);
  const foreignEmail=`foreign-${randomUUID()}@test.dev`;
  assert.equal((await api('POST',`/api/corporate/workspaces/${wsOther.data.id}/members`,{name:'Foreign',email:foreignEmail,role:'creator',password:pass},root.cookie)).status,201);
  assert.equal((await api('POST',`/api/corporate/workspaces/${ws.data.id}/members`,{name:'Foreign',email:foreignEmail,role:'creator'},manager.cookie)).status,409,'corporate cannot claim a creator from another company by email');
  const creatorEmail=`creator-${randomUUID()}@test.dev`;
  const member=await api('POST',`/api/corporate/workspaces/${ws.data.id}/members`,{name:'Writer',email:creatorEmail,role:'creator',password:pass},manager.cookie);
  assert.equal(member.status,201);
  assert.equal(Object.hasOwn(member.data,'password'),false,'provisioning response must not echo supplied password');
  const writer=await api('POST','/api/auth/login',{email:creatorEmail,password:pass});
  assert.equal(writer.status,200);assert.equal(writer.data.role,'creator');
  assert.deepEqual(writer.data.workspaces.map((w:{id:string})=>w.id),[ws.data.id]);
  assert.equal((await api('POST',`/api/corporate/workspaces`,{name:'Forbidden'},writer.cookie)).status,403);
  assert.equal((await api('GET',`/api/bootstrap?workspaceId=${wsOther.data.id}`,undefined,writer.cookie)).status,403);
  assert.equal((await api('POST',`/api/corporate/workspaces/${created.data.id}/members`,{name:'Writer',email:creatorEmail,role:'creator'},manager.cookie)).status,201);
  assert.equal((await api('DELETE',`/api/corporate/workspaces/${created.data.id}`,undefined,manager.cookie)).status,409,'workspace with members cannot be deleted');
  const multi=await api('GET','/api/auth/me',undefined,writer.cookie);
  assert.deepEqual(new Set(multi.data.workspaces.map((w:{id:string})=>w.id)),new Set([ws.data.id,created.data.id]));
  assert.equal((await api('POST',`/api/corporate/workspaces/${wsOther.data.id}/members`,{name:'Writer',email:creatorEmail,role:'creator'},root.cookie)).status,409);
  assert.equal((await api('POST',`/api/corporate/workspaces/${wsOther.data.id}/members`,{name:'X',email:'x@test.dev',role:'creator'},manager.cookie)).status,403);
  assert.equal((await api('GET','/api/auth/me',undefined,writer.cookie)).data.role,'creator');
  assert.equal((await api('POST','/api/drafts',{workspaceId:created.data.id,title:'Creator draft',format:'caption',content:'Original',creatorId:root.data.id},writer.cookie)).status,201,'draft author must be session identity');
  const companyOverview=await api('GET','/api/corporate/dashboard',undefined,manager.cookie);
  assert.equal(companyOverview.status,200);
  assert.equal(companyOverview.data.company.id,co.data.id);
  assert.deepEqual(new Set(companyOverview.data.workspaces.map((w:{id:string})=>w.id)),new Set([ws.data.id,created.data.id]));
  assert.equal(companyOverview.data.workspaces.find((w:{id:string})=>w.id===created.data.id).draftCount,1);
  assert.equal(companyOverview.data.workspaces.find((w:{id:string})=>w.id===ws.data.id).creatorCount,2,'plotted and writer both belong to ws');
  assert.equal(companyOverview.data.workspaces.find((w:{id:string})=>w.id===created.data.id).creatorCount,2,'creator assignments across company workspaces');
  assert.equal(companyOverview.data.userCount,3,'company-wide unique users count excludes superadmin and other company');
  assert.deepEqual(new Set(companyOverview.data.users.map((u:{id:string})=>u.id)),new Set([corp.data.id,plotted.data.id,member.data.id]));
  assert.equal(companyOverview.data.users.find((u:{id:string})=>u.id===member.data.id).workspaces.length,2);
  assert.deepEqual(companyOverview.data.recentDrafts.map((d:{workspaceId:string})=>d.workspaceId),[created.data.id]);
  assert.equal((await api('GET','/api/corporate/dashboard',undefined,writer.cookie)).status,403);
  assert.equal((await api('POST','/api/drafts',{workspaceId:wsOther.data.id,title:'Corporate draft',format:'caption',content:'Company data'},manager.cookie)).status,403);
  assert.equal((await api('POST','/api/drafts',{workspaceId:ws.data.id,title:'Corporate draft',format:'caption',content:'Company data'},manager.cookie)).status,403,'corporate cannot create content even inside company workspace');
  assert.equal((await api('POST','/api/visual/generate',{workspaceId:ws.data.id},manager.cookie)).status,403,'corporate cannot generate visuals');
  assert.equal((await api('PUT','/api/brand-profile',{workspaceId:ws.data.id,organizationName:'X'},manager.cookie)).status,403,'corporate cannot edit brand profile');
  assert.equal((await api('POST','/api/rag/query',{workspaceId:ws.data.id,query:'x'},manager.cookie)).status,403,'corporate cannot run RAG generation');
  assert.equal((await api('POST','/api/drafts',{workspaceId:wsOther.data.id,title:'Global draft',format:'caption',content:'App-wide data'},root.cookie)).status,201,'superadmin may create content globally');
  const afterForeignDraft=await api('GET','/api/corporate/dashboard?companyId='+other.data.id,undefined,manager.cookie);
  assert.equal(afterForeignDraft.status,200);
  assert.equal(afterForeignDraft.data.company.id,co.data.id,'query parameter cannot change company');
  assert.equal(afterForeignDraft.data.recentDrafts.length,1,'other-company drafts never leak');
  const foreignCorp=await api('POST',`/api/corporate/workspaces/${wsOther.data.id}/members`,{name:'Corp',email:corpEmail,role:'creator'},root.cookie);
  assert.equal(foreignCorp.status,409,'corporate account cannot be enrolled in another company as creator');
  const editedCompany=await api('PUT',`/api/admin/companies/${co.data.id}`,{name:'Alpha Updated'},root.cookie);
  assert.equal(editedCompany.status,200);assert.equal(editedCompany.data.name,'Alpha Updated');
  assert.equal((await api('DELETE',`/api/admin/companies/${co.data.id}`,undefined,root.cookie)).status,409,'nonempty company cannot be deleted');
  assert.equal((await api('PUT',`/api/admin/users/${root.data.id}`,{name:'Locked',email,role:'corporate',companyId:co.data.id},root.cookie)).status,409,'self-demotion denied');
  const renamed=await api('PUT',`/api/admin/users/${corp.data.id}`,{name:'Renamed Corp',email:corpEmail,role:'corporate',companyId:co.data.id},root.cookie);
  assert.equal(renamed.status,200);assert.equal(renamed.data.name,'Renamed Corp');
  assert.equal((await api('DELETE',`/api/admin/users/${root.data.id}`,undefined,root.cookie)).status,409,'self-delete denied');
  const updatedWorkspace=await api('PUT',`/api/admin/workspaces/${ws.data.id}`,{companyId:co.data.id,name:'Alpha Renamed',code:ws.data.code,sector:'Water',city:'Jakarta'},root.cookie);
  assert.equal(updatedWorkspace.status,200);assert.equal(updatedWorkspace.data.city,'Jakarta');
  assert.equal((await api('PUT',`/api/admin/workspaces/${ws.data.id}`,{companyId:other.data.id,name:'Moved',code:ws.data.code,sector:'Water',city:'Jakarta'},root.cookie)).status,409,'workspace with members cannot move across companies');
  assert.equal((await api('PUT',`/api/admin/workspaces/${wsOther.data.id}`,{companyId:co.data.id,name:'Moved',code:wsOther.data.code,sector:'Water',city:'Jakarta'},root.cookie)).status,409,'workspace with content cannot move across companies');
  assert.equal((await api('GET','/api/admin/workspaces',undefined,manager.cookie)).status,403);
  assert.equal((await api('DELETE',`/api/admin/workspaces/${ws.data.id}`,undefined,root.cookie)).status,409,'workspace with content cannot be deleted');
  const empty=await api('POST','/api/admin/workspaces',{companyId:other.data.id,name:'Empty',code:`E${randomUUID().slice(0,8)}`,sector:'Water',city:'Jakarta'},root.cookie);
  assert.equal((await api('DELETE',`/api/admin/workspaces/${empty.data.id}`,undefined,manager.cookie)).status,403);
  assert.equal((await api('DELETE',`/api/admin/workspaces/${empty.data.id}`,undefined,root.cookie)).status,200);
  assert.equal((await api('DELETE',`/api/admin/companies/${other.data.id}`,undefined,root.cookie)).status,409);
  const disposable=await api('POST','/api/admin/companies',{name:'Disposable'},root.cookie);
  const tempUser=await api('POST','/api/admin/users',{name:'Temp',email:`temp-${randomUUID()}@test.dev`,password:pass,role:'corporate',companyId:disposable.data.id},root.cookie);
  assert.equal(tempUser.status,201);
  assert.equal((await api('DELETE',`/api/admin/companies/${disposable.data.id}`,undefined,root.cookie)).status,409);
  assert.equal((await api('DELETE',`/api/admin/users/${tempUser.data.id}`,undefined,root.cookie)).status,200);
  assert.equal((await api('DELETE',`/api/admin/users/${tempUser.data.id}`,undefined,root.cookie)).status,404);
  assert.equal((await api('DELETE',`/api/admin/companies/${disposable.data.id}`,undefined,root.cookie)).status,200);
  const overview=await api('GET','/api/admin/overview',undefined,root.cookie);
  assert.equal(overview.status,200);
  assert.equal(overview.data.companies.find((c:{id:string})=>c.id===co.data.id).workspaceCount,2);
  assert.ok(overview.data.users.total>=4);assert.equal(typeof overview.data.drafts,'number');
  assert.equal((await api('GET','/api/admin/overview',undefined,manager.cookie)).status,403);
  const adminCreator=await api('POST','/api/admin/users',{name:'Admin Made',email:`made-${randomUUID()}@test.dev`,password:pass,role:'creator',companyId:co.data.id,workspaceIds:[ws.data.id]},root.cookie);
  assert.equal(adminCreator.status,201);assert.equal(adminCreator.data.role,'creator');
  assert.deepEqual(adminCreator.data.workspaceIds,[ws.data.id]);
  assert.deepEqual((await api('GET','/api/admin/users',undefined,root.cookie)).data.find((u:{id:string})=>u.id===adminCreator.data.id).workspaceIds,[ws.data.id]);
  assert.equal((await api('POST','/api/admin/users',{name:'No Company',email:`nc-${randomUUID()}@test.dev`,password:pass,role:'creator'},root.cookie)).status,400,'creator requires a company');
  assert.equal((await api('POST','/api/admin/users',{name:'Duplicate',email,password:pass,role:'superadmin'},root.cookie)).status,409,'duplicate email is rejected with 409');
  assert.equal((await api('POST','/api/auth/logout',{},writer.cookie)).status,200);
  assert.equal((await api('GET','/api/auth/me',undefined,writer.cookie)).status,401);
});
