import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
process.env.NODE_ENV = 'test';
const { default: app } = await import('./index.ts');
const { pool, runMigrations, clearAllData, hashPassword } = await import('./database.ts');
const server = app.listen(0);
await new Promise<void>(resolve => server.once('listening', resolve));
const base = `http://127.0.0.1:${(server.address() as {port:number}).port}`;
async function api(method:string,path:string,body?:unknown,cookie?:string) {
  const response=await fetch(`${base}${path}`,{method,headers:{'Content-Type':'application/json',Origin:'http://localhost:5173',...(cookie?{Cookie:cookie}:{})},body:body===undefined?undefined:JSON.stringify(body)});
  return {status:response.status,data:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]||''};
}
test.before(async()=>{await runMigrations();await clearAllData();});
test.after(async()=>{await clearAllData();server.close();await pool.end();});

test('three roles: login, company isolation, workspace memberships, global management',async()=>{
  const pass=`longpass-${randomUUID()}`;
  const email=`root-${randomUUID()}@test.dev`;
  await pool.query("INSERT INTO users(id,name,email,password_hash,global_role) VALUES($1,'Root',$2,$3,'superadmin')",[`usr-${randomUUID()}`,email,await hashPassword(pass)]);
  const root=await api('POST','/api/auth/login',{email,password:pass});
  assert.equal(root.status,200);assert.equal(root.data.role,'superadmin');assert.ok(root.cookie);
  const co=await api('POST','/api/admin/companies',{name:'Alpha'},root.cookie);
  assert.equal(co.status,201);
  const other=await api('POST','/api/admin/companies',{name:'Beta'},root.cookie);
  assert.equal(other.status,201);
  assert.equal((await api('POST','/api/admin/users',{name:'Orphan',email:`orphan-${randomUUID()}@test.dev`,password:pass,role:'creator'},root.cookie)).status,400);
  const corpEmail=`corp-${randomUUID()}@test.dev`;
  const corp=await api('POST','/api/admin/users',{name:'Corp',email:corpEmail,password:pass,role:'corporate',companyId:co.data.id},root.cookie);
  assert.equal(corp.status,201);
  const ws=await api('POST','/api/admin/workspaces',{companyId:co.data.id,name:'Alpha One',code:`A${randomUUID().slice(0,8)}`,sector:'Water',city:'Bandung'},root.cookie);
  const wsOther=await api('POST','/api/admin/workspaces',{companyId:other.data.id,name:'Beta One',code:`B${randomUUID().slice(0,8)}`,sector:'Water',city:'Bandung'},root.cookie);
  assert.equal(ws.status,201);assert.equal(wsOther.status,201);
  const manager=await api('POST','/api/auth/login',{email:corpEmail,password:pass});
  assert.equal(manager.status,200);assert.equal(manager.data.role,'corporate');assert.equal(manager.data.companyId,co.data.id);
  assert.deepEqual(manager.data.workspaces.map((w:{id:string})=>w.id),[ws.data.id]);
  assert.equal((await api('GET','/api/admin/users',undefined,manager.cookie)).status,403);
  assert.equal((await api('GET',`/api/bootstrap?workspaceId=${wsOther.data.id}`,undefined,manager.cookie)).status,403);
  const created=await api('POST','/api/corporate/workspaces',{name:'Alpha Two',code:`C${randomUUID().slice(0,8)}`,sector:'Water',city:'Bandung'},manager.cookie);
  assert.equal(created.status,201);
  assert.equal((await api('GET',`/api/bootstrap?workspaceId=${created.data.id}`,undefined,manager.cookie)).status,200);
  const creatorEmail=`creator-${randomUUID()}@test.dev`;
  const member=await api('POST',`/api/corporate/workspaces/${ws.data.id}/members`,{name:'Writer',email:creatorEmail,role:'creator',password:pass},manager.cookie);
  assert.equal(member.status,201);
  assert.equal(Object.hasOwn(member.data,'password'),false,'provisioning response must not echo supplied password');
  const writer=await api('POST','/api/auth/login',{email:creatorEmail,password:pass});
  assert.equal(writer.status,200);assert.equal(writer.data.role,'creator');
  assert.deepEqual(writer.data.workspaces.map((w:{id:string})=>w.id),[ws.data.id]);
  assert.equal((await api('POST',`/api/corporate/workspaces`,{name:'Forbidden'},writer.cookie)).status,403);
  assert.equal((await api('GET',`/api/bootstrap?workspaceId=${wsOther.data.id}`,undefined,writer.cookie)).status,403);
  assert.equal((await api('POST',`/api/corporate/workspaces/${wsOther.data.id}/members`,{name:'Writer',email:creatorEmail,role:'creator'},root.cookie)).status,201);
  const multi=await api('GET','/api/auth/me',undefined,writer.cookie);
  assert.deepEqual(new Set(multi.data.workspaces.map((w:{id:string})=>w.id)),new Set([ws.data.id,wsOther.data.id]));
  assert.equal((await api('POST',`/api/corporate/workspaces/${wsOther.data.id}/members`,{name:'X',email:'x@test.dev',role:'creator'},manager.cookie)).status,403);
  assert.equal((await api('GET','/api/auth/me',undefined,writer.cookie)).data.role,'creator');
  assert.equal((await api('POST','/api/drafts',{workspaceId:wsOther.data.id,title:'Creator draft',format:'caption',content:'Original',creatorId:root.data.id},writer.cookie)).status,201,'draft author must be session identity');
  assert.equal((await api('POST','/api/drafts',{workspaceId:wsOther.data.id,title:'Corporate draft',format:'caption',content:'Company data'},manager.cookie)).status,403);
  assert.equal((await api('POST','/api/drafts',{workspaceId:ws.data.id,title:'Corporate draft',format:'caption',content:'Company data'},manager.cookie)).status,201,'corporate may create content in company workspace without membership');
  assert.equal((await api('POST','/api/drafts',{workspaceId:wsOther.data.id,title:'Global draft',format:'caption',content:'App-wide data'},root.cookie)).status,201,'superadmin may create content globally');
  const foreignCorp=await api('POST',`/api/corporate/workspaces/${wsOther.data.id}/members`,{name:'Corp',email:corpEmail,role:'creator'},root.cookie);
  assert.equal(foreignCorp.status,409,'corporate account cannot be enrolled in another company as creator');
  assert.equal((await api('POST','/api/auth/logout',{},writer.cookie)).status,200);
  assert.equal((await api('GET','/api/auth/me',undefined,writer.cookie)).status,401);
});
